---
kind: pipeline
name: default

steps:
  - name: build analyzers for release
    image: thehiveproject/cortex-worker-builder
    settings:
      worker_path: analyzers
      namespace: cortexneurons
      user: {from_secret: docker_username}
      password: {from_secret: docker_password}
      stable: true
    when:
      event: [tag]

  - name: build responders for release
    image: thehiveproject/cortex-worker-builder
    settings:
      worker_path: responders
      namespace: cortexneurons
      user: {from_secret: docker_username}
      password: {from_secret: docker_password}
      stable: true
    when:
      event: [tag]

  - name: build snapshot analyzers
    image: thehiveproject/cortex-worker-builder
    settings:
      worker_path: analyzers
      namespace: cortexneurons
      user: {from_secret: docker_username}
      password: {from_secret: docker_password}
    when:
      event: {exclude: [tag]}

  - name: build snapshot responders
    image: thehiveproject/cortex-worker-builder
    settings:
      worker_path: responders
      namespace: cortexneurons
      user: {from_secret: docker_username}
      password: {from_secret: docker_password}
    when:
      event: {exclude: [tag]}
